# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-06-26 17:30
from __future__ import unicode_literals

import bunks.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name=b'time bunked')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=bunks.models.get_image_path)),
            ],
        ),
        migrations.AddField(
            model_name='bunk',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_bunk', to='bunks.UserProfile'),
        ),
        migrations.AddField(
            model_name='bunk',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_bunk', to='bunks.UserProfile'),
        ),
    ]
