# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-06-26 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunks', '0005_auto_20190626_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bunk',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'time bunked'),
        ),
    ]
